# -*- coding: utf-8 -*-
"""Customer Segmentation using RFM Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wjnkfSYgxIs6tLYTdgzaxMlG9Imqu_Cx
"""

from google.colab import drive

drive.mount('/content/drive')

# Step 5: Loading dataset
import pandas as pd

# Assuming you have a CSV file named 'customer_data.csv'
customer_data = pd.read_excel('/content/drive/MyDrive/Online_Retail.xlsx')

# Step 6: Removing duplicates
customer_data = customer_data.drop_duplicates()

# Step 7: Data insights
print(customer_data.head())

# Step 8: RFM Analysis
from datetime import datetime

current_date = pd.to_datetime('today')
customer_data['Recency'] = (current_date - pd.to_datetime(customer_data['InvoiceDate'])).dt.days

# ii. Frequency: Calculate the number of orders for each customer
frequency_df = customer_data.groupby('CustomerID')['InvoiceNo'].nunique().reset_index()
frequency_df.columns = ['CustomerID', 'Frequency']

# iii. Monetary: Calculate the sum of purchase price for each customer
monetary_df = customer_data.groupby('CustomerID')['UnitPrice'].sum().reset_index()
monetary_df.columns = ['CustomerID', 'Monetary']

# Merge the Recency, Frequency, and Monetary DataFrames using CustomerID as the key
rfm_df = pd.merge(frequency_df, monetary_df, on='CustomerID', how='left')
rfm_df = pd.merge(rfm_df, customer_data[['CustomerID', 'Recency']], on='CustomerID', how='left')

# Display the RFM DataFrame
print(rfm_df.head())